### ISSUE TITLE
First interaction with git remote takes long on Windows

### ISSUE THREAD

**Issue by sfavazza-duagon** [magit/ssh-agency#21]
**Context**

Lately I had some hard time using SSH keys to interact with a remote on my Windows machine. At a certain point whenever I was pulling/fetchin/pushing from an SSH-configured repository, emacs hanged for long time (even up to 3 minutes). This issue was observed only at the first interaction with the remote.

Having a look at the Windows task manager I could observe that during the hang time an *ssh-add* process was frequently changing its own PID. 

After some debugging I realized that the issue was caused by hundreds of SSH sockets in the temp folder not anymore associated to an agent. As ssh-agency tries to identify a running ssh-agent by using the found sockets, a new process of ssh-add is created for each of them (hence the frequently changing PID in the ssh-add process).

**Possible Improvements**

Despite this issue might be related to my case only, if would be nice having a slightly more verbose tool, such that the user is informed that there are many ssh socket folders.
Moreover after any failing ssh-agent search _ssh-agency_ might delete the current stale SSH socket.

If you think that it might be helpful please let me know and I will work to a patch (better not to start working on something that is not useful to many :wink: )

**Comment by tarsius** [comment]
I think this is the fault of whatever is creating unassociated sockets.

> Despite this issue might be related to my case only, if would be nice having a slightly more verbose tool, such that the user is informed that there are many ssh socket folders.

@npostavs isn't really active anymore and I do not use Windows and have never used this package. So yes, it might be nice to warn about this but since you indeed seem to be only one who has/had this problem (or at least the only one who bothered to report it), I am closing this, indicating that I have no intention to do anything about it.
