### ISSUE TITLE
Pushing on Linux is broken. 

### ISSUE THREAD

**Issue by PythonNut** [magit/ssh-agency#8]
I can't push on Linux to a repo using a *git://* url by default. (even with `emacs-24.5 -Q`) 

* This is because `ssh-agency-add-executable` and `ssh-agency-agent-executable` are both `nil`. 
* This is because `ssh-agency-executable-find` is told to find windows `*.exe` files by default.

Furthermore, if I evaluate:
```emacs
(setq ssh-agency-add-executable (ssh-agency-executable-find "ssh-add"))
(setq ssh-agency-agent-executable (ssh-agency-executable-find "ssh-agent"))

```

Then I get the error `ssh-agency-add-keys: Symbol's function definition is void: w32-short-file-name`. 

I almost feel like `ssh-agency` was not intended for use with Linux. Is this some mistake of mine?

**Comment by npostavs** [comment]
> I almost feel like ssh-agency was not intended for use with Linux. Is this some mistake of mine?

Not a mistake, it's indeed intended for Windows. Until recently it was only activated on Windows, but when I changed to use hooks instead of advice, I now realize I dropped the `system-type` check (a220c1ff1bbc8196235233a1b466d7ff2bfad786).

That said, it *could* be extended to work on non-Windows platforms as well, I've seen some posts about people having trouble ssh-agent on GNU/Linux.

**Comment by PythonNut** [comment]
@npostavs Ah, I see.

At least for me, it's not entirely clear what `ssh-agency` does. I understand it has something to do with managing `ssh-agents`, which is something that annoys me on Linux personally, but I don't quite know how it's supposed to affect my workflow.

I'd be willing to test this on Linux, but I can't contribute very much because I don't understand what's going on.

**Comment by npostavs** [comment]
To let git use ssh-agent successfully, there needs to be a running ssh-agent (of course), and git needs the environment variables `SSH_AGENT_PID` and `SSH_AUTH_SOCK` to be pointing at that agent. 

#### On Unixish platforms, 

This should generally happen by starting up the ssh-agent in your shell login script, the agent prints out shell code that you can eval to set the environment variables which will then be passed down to every process you run from then on. So in theory, everything will Just Work, and there's no need of something like `ssh-agency`.

#### On Windows, 

git comes with a bash shell, which is of course not the login shell, so starting ssh-agent upon login isn't so straightforward. Furthermore, since Windows doesn't have ptys, entering the passphrase away from the command line (e.g. from Emacs) is quite a bit trickier.

`ssh-agency` takes care of these problems by hunting down the running `ssh-agent` (or starting one if there isn't any) and setting the environment variables in Emacs to point to it. It also does some extra environment variable wrangling to get a graphical passphrase prompt in Emacs (or for earlier git versions, popup a console window).

---

> I understand it has something to do with managing `ssh-agents`, which is something that annoys me on Linux personally, but I don't quite know how it's supposed to affect my workflow.

I'm not sure what "annoys" means in concrete terms, but if you can describe how your workflow differs from the ideal "Unixish" one described above, we can see if `ssh-agency` might be useful.

**Comment by PythonNut** [comment]
> This should generally happen by starting up the ssh-agent in your shell login script, the agent prints out shell code that you can eval to set the environment variables which will then be passed down to every process you run from then on. So in theory, everything will Just Work, and there's no need of something like `ssh-agency`.

> [...]

> I'm not sure what "annoys" means in concrete terms, but if you can describe how your workflow differs from the ideal "Unixish" one described above, we can see if ssh-agency might be useful.


Ah I understand. The problem is not really running `ssh-agent`, it's adding the keys afterwards. My keys require a password to add. I don't always use my ssh keys, and I don't use any keychain helper to automate the unlocking. I'd rather not type the password every time I log in, because I myself log into my machines with SSH, and my sessions are often short and usually don't require pushes. Unfortunately, [adding keys on-demand is not currently possible](http://superuser.com/questions/325662/how-to-make-ssh-agent-automatically-add-the-key-on-demand).

Currently, I just type the password out whenever I access the remote. However, any solution that could also start and add my SSH keys at the application level would be perfect.

I realize that this issue tracker is not for troubleshooting and advice, but, as far as I know, there isn't an elegant solution for my needs at the moment.

**Comment by npostavs** [comment]
Ah, well actually `ssh-agency` does sort of solve this. Keys are only added when git is about to do a remote operation. Although it doesn't distinguish between remotes (I don't know of a practical way of doing so), so ssh keys would be added (and passphrase prompted for) even if you push to an https remote.

> However, any solution that could also start and add my SSH keys at the application level would be perfect.

By default `ssh-agency-ensure` (which both starts agent and adds keys) is added to `magit-credential-hook`. `ssh-agency-start-agent` and `ssh-agency-add-keys` can be used separately if needed.

> I realize that this issue tracker is not for troubleshooting and advice

So far it has much lower traffic than magit's, so we can be a bit more relaxed about this :)

**Comment by npostavs** [comment]
> Unfortunately, adding keys on-demand is not currently possible.

I've found https://github.com/ccontavalli/ssh-ident which claims to do this, might be better.

**Comment by PythonNut** [comment]
> By default `ssh-agency-ensure` (which both starts agent and adds keys) is added to `magit-credential-hook`. `ssh-agency-start-agent` and `ssh-agency-add-keys` can be used separately if needed.

However, neither will work with Linux at the moment, correct? 

> I've found https://github.com/ccontavalli/ssh-ident which claims to do this, might be better.

That looks interesting. I could probably roll a solution together for myself, but were you thinking of implementing something more general?

> So far it has much lower traffic than magit's, so we can be a bit more relaxed about this :)

Thanks :)

**Comment by npostavs** [comment]
> However, neither will work with Linux at the moment, correct?

Yes, but I think it shouldn't be too hard to fix that. Basically, don't use `.exe` extension, and avoid the `SSH_ASKPASS` related hacks.

> That looks interesting. I could probably roll a solution together for myself, but were you thinking of implementing something more general?

Haven't really decided yet.

**Comment by npostavs** [comment]
> Yes, but I think it shouldn't be too hard to fix that. Basically, don't use .exe extension, and avoid the SSH_ASKPASS related hacks.

Done at [xplatform](https://github.com/magit/ssh-agency/compare/xplatform), please try it out.

**Comment by PythonNut** [comment]
@npostavs just tested. It works great on Linux.
